#!/usr/bin/env bash
# apply-branding.sh — propagate libresynergy.env branding across the running stack.
# Portable + safe to re-run: every step is guarded on the service actually running.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
[ -f "$ROOT/libresynergy.env" ] || { echo "no libresynergy.env — run ./bin/ls init"; exit 1; }
set -a; . "$ROOT/libresynergy.env"; set +a
for v in LS_DATA_DIR LS_WWW_DIR LS_SECRETS_DIR; do
  eval "$v=\"\$(cd \"\$ROOT\" && realpath -m \"\${$v:-./}\")\""; export "$v"
done

dc(){ docker compose --project-directory "$ROOT" -f "$ROOT/docker-compose.yml" "$@"; }
running(){ dc ps --status running --services 2>/dev/null | grep -qx "$1"; }
say(){ printf '  • %s\n' "$*"; }

echo "LibreSynergy → applying brand '${LS_BRAND_NAME}' (${LS_BASE_DOMAIN})"

# 1) Palette → central CSS tokens (read by shell, landing, checkout)
install -d "${LS_WWW_DIR}/brand"
cat > "${LS_WWW_DIR}/brand/tokens.css" <<EOF
/* ${LS_BRAND_NAME} brand tokens — powered by ${LS_POWERED_BY}. Generated by apply-branding.sh */
:root{
  --ls-ink:${LS_COLOR_INK};
  --ls-brand:${LS_COLOR_BRAND};
  --ls-gold:${LS_COLOR_ACCENT};
  --ls-gradient:linear-gradient(135deg,${LS_COLOR_BRAND} 0%,${LS_COLOR_ACCENT} 100%);
}
EOF
say "wrote ${LS_WWW_DIR}/brand/tokens.css"

# 2) Authentik — re-apply branding blueprint (if the worker is up and a blueprint exists)
if running worker; then
  dc exec -T worker ak apply_blueprint /blueprints/custom/branding.yaml >/dev/null 2>&1 \
    && say "Authentik branding blueprint applied" || say "Authentik: no custom branding blueprint (skipped)"
fi

# 3) Frappe LMS — app name + footer
if running app; then
  dc exec -T app bash -lc "cd /home/frappe/frappe-bench && \
    printf \"import frappe; d=frappe.get_doc('Website Settings'); d.app_name='${LS_BRAND_NAME}'; d.footer_powered='Powered by ${LS_POWERED_BY}'; d.save(ignore_permissions=True); frappe.db.commit()\" \
    | bench --site ${LS_LEARN} console" >/dev/null 2>&1 \
    && say "Frappe LMS app_name set to ${LS_BRAND_NAME}" || say "Frappe LMS: skipped"
fi

# 4) Jitsi — app/provider name (recreate meet web after)
JF="${LS_DATA_DIR}/jitsi/web/custom-interface_config.js"
if [ -f "$JF" ]; then
  sed -i "s/interfaceConfig.APP_NAME = .*/interfaceConfig.APP_NAME = '${LS_BRAND_NAME}';/" "$JF" 2>/dev/null || true
  say "Jitsi APP_NAME set (recreate meet: ./bin/ls restart jitsi-web)"
fi

echo "Done. Chat client name/logo are compiled in — rebuild apps/chat_cinny then ./bin/ls up -d --build."
