#!/usr/bin/env python3
"""
libresynergy admin — one dashboard to run the community.

Sections: branding (live edit -> env + tokens.css + full re-apply via host cron),
sponsors (rendered on the landing page), site banner + Matrix announcements,
service health, launch checklist, quick links.

Pure stdlib, loopback-only; Caddy fronts https://admin.<domain> behind
Authentik forward-auth. The app additionally requires the admin group header.
"""
import json, os, re, threading, time, urllib.request, urllib.error, html, uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

LISTEN_HOST = os.environ.get("LISTEN_HOST", "127.0.0.1")
LISTEN_PORT = int(os.environ.get("LISTEN_PORT", "9110"))
LS_ENV = os.environ.get("LS_ENV_FILE", "/ls/libresynergy.env")
WWW = os.environ.get("WWW_DIR", "/www")
STATE = os.environ.get("STATE_DIR", "/state")
ADMIN_GROUP = os.environ.get("ADMIN_GROUP", "authentik Admins")
MATRIX_HS = os.environ.get("MATRIX_HS_URL", "http://127.0.0.1:8008").rstrip("/")
BOT_TOKEN = os.environ.get("MATRIX_BOT_TOKEN", "")
ANNOUNCE_ROOM = os.environ.get("ANNOUNCE_ROOM", "")

SPONSORS = os.path.join(WWW, "brand", "sponsors.json")
BANNER = os.path.join(WWW, "brand", "banner.json")
FLAG = os.path.join(STATE, "apply-branding.requested")
LOG = os.path.join(STATE, "apply-branding.log")

BRAND_KEYS = ["LS_BRAND_NAME", "LS_BRAND_TAGLINE", "LS_POWERED_BY",
              "LS_COLOR_BRAND", "LS_COLOR_ACCENT", "LS_COLOR_INK"]
_lock = threading.Lock()

# ---------- helpers -----------------------------------------------------------
def env_read():
    vals = {}
    try:
        for line in open(LS_ENV):
            m = re.match(r'^([A-Z_]+)=(?:"([^"]*)"|(.*))$', line.strip())
            if m: vals[m.group(1)] = m.group(2) if m.group(2) is not None else m.group(3)
    except FileNotFoundError:
        pass
    return vals

def env_write(updates):
    lines = open(LS_ENV).read().splitlines(keepends=False)
    out = []
    seen = set()
    for line in lines:
        m = re.match(r'^([A-Z_]+)=', line)
        if m and m.group(1) in updates:
            out.append(f'{m.group(1)}="{updates[m.group(1)]}"')
            seen.add(m.group(1))
        else:
            out.append(line)
    for k, v in updates.items():
        if k not in seen: out.append(f'{k}="{v}"')
    open(LS_ENV, "w").write("\n".join(out) + "\n")

def tokens_css(v):
    path = os.path.join(WWW, "brand", "tokens.css")
    open(path, "w").write(
        f"""/* {v.get('LS_BRAND_NAME','')} brand tokens — generated by the admin dashboard */
:root{{
  --ls-ink:{v.get('LS_COLOR_INK','#0b0b12')};
  --ls-brand:{v.get('LS_COLOR_BRAND','#7c6cff')};
  --ls-gold:{v.get('LS_COLOR_ACCENT','#ffc15e')};
  --ls-gradient:linear-gradient(135deg,{v.get('LS_COLOR_BRAND','#7c6cff')} 0%,{v.get('LS_COLOR_ACCENT','#ffc15e')} 100%);
}}
""")

def jload(path, default):
    try: return json.load(open(path))
    except Exception: return default

def jsave(path, data):
    tmp = path + ".tmp"
    json.dump(data, open(tmp, "w"), indent=1)
    os.replace(tmp, path)

def port_check(port, path="/", host="127.0.0.1", timeout=3):
    try:
        with urllib.request.urlopen(f"http://{host}:{port}{path}", timeout=timeout) as r:
            return r.status < 500
    except urllib.error.HTTPError as e:
        return e.code < 500
    except Exception:
        return False

def matrix_announce(text):
    if not (BOT_TOKEN and ANNOUNCE_ROOM): return False, "bot token or room not configured"
    room = urllib.parse.quote(ANNOUNCE_ROOM)
    url = f"{MATRIX_HS}/_matrix/client/v3/rooms/{room}/send/m.room.message/{uuid.uuid4()}"
    req = urllib.request.Request(url, method="PUT",
        data=json.dumps({"msgtype": "m.text", "body": text}).encode(),
        headers={"Authorization": f"Bearer {BOT_TOKEN}", "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return True, json.load(r).get("event_id", "sent")
    except urllib.error.HTTPError as e:
        return False, f"matrix {e.code}: {e.read().decode()[:200]}"

import urllib.parse

SERVICES = [  # label, port, path
    ("SSO (Authentik)", 8300, "/-/health/live/"),
    ("Matrix (Synapse)", 8008, "/health"),
    ("Chat web", 8114, "/"),
    ("Classroom (LMS)", 8100, "/"),
    ("Webinars (Jitsi)", 8200, "/"),
    ("Payments bridge", 9092, "/healthz"),
    ("Livestream (OwnCast)", 8600, "/"),
    ("BTCPay", 8500, "/"),
    ("Events API", 9102, "/api/events"),
]

# ---------- page --------------------------------------------------------------
PAGE = """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>__BRAND__ — admin</title>
<link rel="icon" href="/brand-favicon" type="image/x-icon">
<style>
:root{--brand:__CBRAND__;--gold:__CACCENT__;--ink:#0d0d15;--card:#15151f;--mut:#8b8b9e;--ok:#3ecf8e;--bad:#ff6b6b}
*{box-sizing:border-box;margin:0}body{background:var(--ink);color:#ececf4;font:15px/1.5 system-ui,sans-serif;padding:24px;max-width:1100px;margin:0 auto}
h1{font-size:22px;margin-bottom:2px}h1 b{background:linear-gradient(135deg,var(--brand),var(--gold));-webkit-background-clip:text;background-clip:text;color:transparent}
h2{font-size:15px;margin:0 0 12px;color:var(--gold)}
.sub{color:var(--mut);margin-bottom:24px;font-size:13px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}
.card{background:var(--card);border:1px solid #23233247;border-radius:14px;padding:18px}
label{display:block;font-size:12px;color:var(--mut);margin:10px 0 3px}
input[type=text],textarea{width:100%;background:#0d0d15;border:1px solid #2b2b3d;border-radius:8px;color:#ececf4;padding:8px 10px;font:inherit}
input[type=color]{border:none;background:none;width:44px;height:30px;padding:0;vertical-align:middle}
button{background:linear-gradient(135deg,var(--brand),var(--gold));border:none;border-radius:8px;color:#0d0d15;font-weight:700;padding:9px 16px;margin-top:12px;cursor:pointer}
button.ghost{background:#2b2b3d;color:#ececf4;font-weight:500}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.pill{display:inline-flex;align-items:center;gap:6px;background:#0d0d15;border-radius:20px;padding:4px 12px;font-size:13px;margin:3px 4px 3px 0}
.dot{width:8px;height:8px;border-radius:50%}.ok{background:var(--ok)}.bad{background:var(--bad)}
.spon{display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid #23233247;font-size:14px}
a{color:var(--gold);text-decoration:none}
.links a{display:inline-block;background:#0d0d15;border-radius:8px;padding:8px 14px;margin:4px 6px 0 0;font-size:13px}
.note{font-size:12px;color:var(--mut);margin-top:8px}
#toast{position:fixed;bottom:20px;right:20px;background:var(--brand);color:#fff;padding:10px 18px;border-radius:10px;display:none}
.check{font-size:14px;padding:3px 0}
</style></head><body>
<h1><b>__BRAND__</b> admin</h1>
<div class="sub">__TAGLINE__ · libresynergy control panel · signed in as <span id="who">…</span></div>
<div class="grid">

<div class="card"><h2>Branding</h2>
<label>Community name</label><input type="text" id="b_name">
<label>Tagline</label><input type="text" id="b_tag">
<label>Powered-by footer (empty to hide)</label><input type="text" id="b_pow">
<div class="row" style="margin-top:10px">
  <span><label>Brand</label><input type="color" id="b_brand"></span>
  <span><label>Accent</label><input type="color" id="b_accent"></span>
  <span><label>Ink</label><input type="color" id="b_ink"></span>
</div>
<button onclick="saveBrand()">Save + apply everywhere</button>
<div class="note">Colors/name land instantly on the landing, app shell and checkout;
Authentik / classroom / webinar rebrand runs within a minute.</div></div>

<div class="card"><h2>Sponsors</h2>
<div id="sponsors"></div>
<label>Name</label><input type="text" id="s_name" placeholder="Acme Corp">
<label>Link</label><input type="text" id="s_url" placeholder="https://…">
<label>Logo URL (optional, shown instead of name)</label><input type="text" id="s_logo" placeholder="/brand/acme.svg">
<button onclick="addSponsor()">Add sponsor</button>
<div class="note">Shown in the sponsors strip on the landing page, in order added.</div></div>

<div class="card"><h2>Messaging</h2>
<label>Site banner (shows on landing; empty = hidden)</label><input type="text" id="m_banner">
<label>Banner link (optional)</label><input type="text" id="m_burl">
<button onclick="saveBanner()">Set banner</button> <button class="ghost" onclick="clearBanner()">Clear</button>
<label style="margin-top:16px">Announcement → community chat</label>
<textarea id="m_ann" rows="3" placeholder="We're live tonight at 8pm…"></textarea>
<button onclick="announce()">Send to #general</button></div>

<div class="card"><h2>Service health</h2><div id="health">checking…</div>
<h2 style="margin-top:16px">Launch checklist</h2><div id="launch"></div></div>

<div class="card"><h2>Quick links</h2><div class="links">
<a href="https://auth.__DOMAIN__/if/admin/" target="_blank">Authentik admin</a>
<a href="https://live.__DOMAIN__/admin" target="_blank">OwnCast admin</a>
<a href="https://btcpay.__DOMAIN__" target="_blank">BTCPay</a>
<a href="https://learn.__DOMAIN__" target="_blank">Classroom</a>
<a href="https://__DOMAIN__" target="_blank">Landing</a>
<a href="https://auth.__DOMAIN__/if/flow/community-signup/" target="_blank">Signup flow</a>
</div></div>

</div>
<div id="toast"></div>
<script>
const $=id=>document.getElementById(id);
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2600)}
async function api(m,p,b){const r=await fetch(p,{method:m,headers:{"Content-Type":"application/json"},body:b?JSON.stringify(b):undefined});if(!r.ok){toast("error: "+await r.text());throw 0}return r.json()}
async function load(){
  const s=await api("GET","/api/state");
  $("who").textContent=s.user||"?";
  $("b_name").value=s.brand.LS_BRAND_NAME||"";$("b_tag").value=s.brand.LS_BRAND_TAGLINE||"";
  $("b_pow").value=s.brand.LS_POWERED_BY||"";
  $("b_brand").value=s.brand.LS_COLOR_BRAND||"#7c6cff";$("b_accent").value=s.brand.LS_COLOR_ACCENT||"#ffc15e";$("b_ink").value=s.brand.LS_COLOR_INK||"#0b0b12";
  $("m_banner").value=s.banner.text||"";$("m_burl").value=s.banner.url||"";
  renderSponsors(s.sponsors);
  $("health").innerHTML=s.health.map(h=>`<span class="pill"><span class="dot ${h[1]?"ok":"bad"}"></span>${h[0]}</span>`).join("");
  $("launch").innerHTML=s.launch.map(c=>`<div class="check">${c[1]?"✅":"⬜"} ${c[0]}</div>`).join("");
}
function renderSponsors(list){
  $("sponsors").innerHTML=list.map((s,i)=>`<div class="spon"><span><a href="${s.url}" target="_blank">${s.name}</a></span><button class="ghost" style="margin:0;padding:3px 10px" onclick="delSponsor(${i})">remove</button></div>`).join("")||'<div class="note">none yet</div>';
}
async function saveBrand(){await api("POST","/api/branding",{LS_BRAND_NAME:$("b_name").value,LS_BRAND_TAGLINE:$("b_tag").value,LS_POWERED_BY:$("b_pow").value,LS_COLOR_BRAND:$("b_brand").value,LS_COLOR_ACCENT:$("b_accent").value,LS_COLOR_INK:$("b_ink").value});toast("branding saved — full re-apply queued")}
async function addSponsor(){const r=await api("POST","/api/sponsors",{name:$("s_name").value,url:$("s_url").value,logo:$("s_logo").value});renderSponsors(r.sponsors);$("s_name").value=$("s_url").value=$("s_logo").value="";toast("sponsor added")}
async function delSponsor(i){const r=await api("DELETE","/api/sponsors?i="+i);renderSponsors(r.sponsors);toast("removed")}
async function saveBanner(){await api("POST","/api/banner",{text:$("m_banner").value,url:$("m_burl").value});toast("banner set")}
async function clearBanner(){await api("POST","/api/banner",{text:"",url:""});$("m_banner").value="";toast("banner cleared")}
async function announce(){const r=await api("POST","/api/announce",{text:$("m_ann").value});$("m_ann").value="";toast("announced: "+r.id)}
load();setInterval(load,30000);
</script></body></html>"""

# ---------- http --------------------------------------------------------------
class H(BaseHTTPRequestHandler):
    def _send(self, code, body, ctype="application/json"):
        data = body if isinstance(body, bytes) else json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(data)

    def _admin(self):
        groups = self.headers.get("X-authentik-groups", "")
        if ADMIN_GROUP not in [g.strip() for g in groups.split("|")]:
            self._send(403, {"error": f"requires group '{ADMIN_GROUP}'"})
            return False
        return True

    def do_GET(self):
        if self.path == "/healthz":
            return self._send(200, {"ok": True})
        if not self._admin(): return
        if self.path == "/brand-favicon":
            try: return self._send(200, open(os.path.join(WWW, "brand", "favicon.ico"), "rb").read(), "image/x-icon")
            except Exception: return self._send(404, {"error": "no favicon"})
        if self.path == "/api/state":
            v = env_read()
            health = [(n, port_check(p, path)) for n, p, path in SERVICES]
            hs = dict((n, ok) for n, ok, in health)
            stripe_on = False
            try:
                with urllib.request.urlopen("http://127.0.0.1:9092/healthz", timeout=3) as r:
                    j = json.load(r); stripe_on = j.get("stripe", False); btc_on = j.get("btcpay", False)
            except Exception: btc_on = False
            launch = [
                ("Stripe live checkout wired", stripe_on),
                ("BTCPay store wired to bridge", btc_on),
                ("Livestream up (OwnCast)", hs.get("Livestream (OwnCast)", False)),
                ("SSO up (Authentik)", hs.get("SSO (Authentik)", False)),
                ("Chat + federation up (Synapse)", hs.get("Matrix (Synapse)", False)),
            ]
            return self._send(200, {
                "user": self.headers.get("X-authentik-username", ""),
                "brand": {k: v.get(k, "") for k in BRAND_KEYS + ["LS_BASE_DOMAIN"]},
                "sponsors": jload(SPONSORS, []),
                "banner": jload(BANNER, {}),
                "health": health, "launch": launch})
        if self.path == "/":
            v = env_read()
            page = (PAGE.replace("__BRAND__", html.escape(v.get("LS_BRAND_NAME", "LibreSynergy")))
                        .replace("__TAGLINE__", html.escape(v.get("LS_BRAND_TAGLINE", "")))
                        .replace("__DOMAIN__", v.get("LS_BASE_DOMAIN", ""))
                        .replace("__CBRAND__", v.get("LS_COLOR_BRAND", "#7c6cff"))
                        .replace("__CACCENT__", v.get("LS_COLOR_ACCENT", "#ffc15e")))
            return self._send(200, page.encode(), "text/html; charset=utf-8")
        self._send(404, {"error": "not found"})

    def do_POST(self):
        if not self._admin(): return
        try:
            body = json.loads(self.rfile.read(int(self.headers.get("Content-Length", 0)) or 0) or b"{}")
        except Exception:
            return self._send(400, {"error": "bad json"})
        with _lock:
            if self.path == "/api/branding":
                updates = {k: str(body.get(k, "")).strip() for k in BRAND_KEYS if k in body}
                for ck in ("LS_COLOR_BRAND", "LS_COLOR_ACCENT", "LS_COLOR_INK"):
                    if ck in updates and not re.fullmatch(r"#[0-9a-fA-F]{6}", updates[ck]):
                        return self._send(400, {"error": f"{ck} must be #rrggbb"})
                env_write(updates)
                tokens_css(env_read())
                open(FLAG, "w").write(str(time.time()))   # host cron runs apply-branding.sh
                return self._send(200, {"ok": True})
            if self.path == "/api/sponsors":
                if not body.get("name") or not body.get("url"):
                    return self._send(400, {"error": "name and url required"})
                lst = jload(SPONSORS, [])
                lst.append({"name": body["name"][:80], "url": body["url"][:300], "logo": body.get("logo", "")[:300]})
                jsave(SPONSORS, lst)
                return self._send(200, {"ok": True, "sponsors": lst})
            if self.path == "/api/banner":
                jsave(BANNER, {"text": str(body.get("text", ""))[:300], "url": str(body.get("url", ""))[:300]})
                return self._send(200, {"ok": True})
            if self.path == "/api/announce":
                text = str(body.get("text", "")).strip()
                if not text: return self._send(400, {"error": "empty"})
                ok, info = matrix_announce(text)
                return self._send(200 if ok else 502, {"ok": ok, "id": info})
        self._send(404, {"error": "not found"})

    def do_DELETE(self):
        if not self._admin(): return
        if self.path.startswith("/api/sponsors"):
            q = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            i = int(q.get("i", ["-1"])[0])
            with _lock:
                lst = jload(SPONSORS, [])
                if 0 <= i < len(lst): lst.pop(i)
                jsave(SPONSORS, lst)
            return self._send(200, {"ok": True, "sponsors": lst})
        self._send(404, {"error": "not found"})

    def log_message(self, fmt, *a):
        print(f"{time.strftime('%FT%T')} {self.headers.get('X-authentik-username','-')} {fmt % a}")

if __name__ == "__main__":
    os.makedirs(STATE, exist_ok=True)
    print(f"libresynergy-admin on {LISTEN_HOST}:{LISTEN_PORT} (admin group: {ADMIN_GROUP})")
    ThreadingHTTPServer((LISTEN_HOST, LISTEN_PORT), H).serve_forever()
