#!/usr/bin/env python3
"""
libresynergy admin — one dashboard to run the community.

Sections: branding (live edit -> env + tokens.css + full re-apply via host cron),
sponsors (rendered on the landing page), site banner + Matrix announcements,
service health, launch checklist, quick links.

Pure stdlib, loopback-only; Caddy fronts https://admin.<domain> behind
Authentik forward-auth. The app additionally requires the admin group header.

UI is localized (en/es/fr) via the shared /i18n catalog: language is resolved
per request (?lang= > ls_lang cookie > Accept-Language > LS_DEFAULT_LANG > en).
"""
import json, os, re, sys, threading, time, urllib.request, urllib.error, urllib.parse, html, uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# Shared translation helper — mounted at /i18n, or reachable via the repo mount.
for _p in ("/i18n", "/ls/apps/i18n"):
    if os.path.isdir(_p) and _p not in sys.path:
        sys.path.insert(0, _p)
        break
import i18n

LISTEN_HOST = os.environ.get("LISTEN_HOST", "127.0.0.1")
LISTEN_PORT = int(os.environ.get("LISTEN_PORT", "9110"))
LS_ENV = os.environ.get("LS_ENV_FILE", "/ls/libresynergy.env")
WWW = os.environ.get("WWW_DIR", "/www")
STATE = os.environ.get("STATE_DIR", "/state")
ADMIN_GROUP = os.environ.get("ADMIN_GROUP", "authentik Admins")
MATRIX_HS = os.environ.get("MATRIX_HS_URL", "http://127.0.0.1:8008").rstrip("/")
BOT_TOKEN = os.environ.get("MATRIX_BOT_TOKEN", "")
ANNOUNCE_ROOM = os.environ.get("ANNOUNCE_ROOM", "")

SPONSORS = os.path.join(WWW, "brand", "sponsors.json")
BANNER = os.path.join(WWW, "brand", "banner.json")
FLAG = os.path.join(STATE, "apply-branding.requested")
LOG = os.path.join(STATE, "apply-branding.log")

BRAND_KEYS = ["LS_BRAND_NAME", "LS_BRAND_TAGLINE", "LS_POWERED_BY",
              "LS_COLOR_BRAND", "LS_COLOR_ACCENT", "LS_COLOR_INK"]
_lock = threading.Lock()

# ---------- helpers -----------------------------------------------------------
def env_read():
    vals = {}
    try:
        for line in open(LS_ENV):
            m = re.match(r'^([A-Z_]+)=(?:"([^"]*)"|(.*))$', line.strip())
            if m: vals[m.group(1)] = m.group(2) if m.group(2) is not None else m.group(3)
    except FileNotFoundError:
        pass
    return vals

def env_write(updates):
    lines = open(LS_ENV).read().splitlines(keepends=False)
    out = []
    seen = set()
    for line in lines:
        m = re.match(r'^([A-Z_]+)=', line)
        if m and m.group(1) in updates:
            out.append(f'{m.group(1)}="{updates[m.group(1)]}"')
            seen.add(m.group(1))
        else:
            out.append(line)
    for k, v in updates.items():
        if k not in seen: out.append(f'{k}="{v}"')
    open(LS_ENV, "w").write("\n".join(out) + "\n")

def tokens_css(v):
    path = os.path.join(WWW, "brand", "tokens.css")
    open(path, "w").write(
        f"""/* {v.get('LS_BRAND_NAME','')} brand tokens — generated by the admin dashboard */
:root{{
  --ls-ink:{v.get('LS_COLOR_INK','#0b0b12')};
  --ls-brand:{v.get('LS_COLOR_BRAND','#7c6cff')};
  --ls-gold:{v.get('LS_COLOR_ACCENT','#ffc15e')};
  --ls-gradient:linear-gradient(135deg,{v.get('LS_COLOR_BRAND','#7c6cff')} 0%,{v.get('LS_COLOR_ACCENT','#ffc15e')} 100%);
}}
""")

def jload(path, default):
    try: return json.load(open(path))
    except Exception: return default

def jsave(path, data):
    tmp = path + ".tmp"
    json.dump(data, open(tmp, "w"), indent=1)
    os.replace(tmp, path)

def port_check(port, path="/", host="127.0.0.1", timeout=3):
    try:
        with urllib.request.urlopen(f"http://{host}:{port}{path}", timeout=timeout) as r:
            return r.status < 500
    except urllib.error.HTTPError as e:
        return e.code < 500
    except Exception:
        return False

def matrix_announce(text):
    if not (BOT_TOKEN and ANNOUNCE_ROOM): return False, "bot token or room not configured"
    room = urllib.parse.quote(ANNOUNCE_ROOM)
    url = f"{MATRIX_HS}/_matrix/client/v3/rooms/{room}/send/m.room.message/{uuid.uuid4()}"
    req = urllib.request.Request(url, method="PUT",
        data=json.dumps({"msgtype": "m.text", "body": text}).encode(),
        headers={"Authorization": f"Bearer {BOT_TOKEN}", "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return True, json.load(r).get("event_id", "sent")
    except urllib.error.HTTPError as e:
        return False, f"matrix {e.code}: {e.read().decode()[:200]}"

SERVICES = [  # stable id (i18n key svc.<id> + launch lookups), port, health path
    ("sso", 8300, "/-/health/live/"),
    ("matrix", 8008, "/health"),
    ("chatweb", 8114, "/"),
    ("lms", 8100, "/"),
    ("jitsi", 8200, "/"),
    ("bridge", 9092, "/healthz"),
    ("owncast", 8600, "/"),
    ("btcpay", 8500, "/"),
    ("events", 9102, "/api/events"),
]

# ---------- page --------------------------------------------------------------
# Plain template (not an f-string) so CSS/JS braces stay literal; __TOKENS__ are
# substituted in render_page() with per-request translations + brand values.
PAGE = """<!doctype html><html lang="__LANG__"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>__T_title__</title>
<link rel="icon" href="/brand-favicon" type="image/x-icon">
<link rel="stylesheet" href="https://yaya.sh/brand/system.css">
<style>
:root{--brand:__CBRAND__;--gold:__CACCENT__;--ink:var(--ls-ink);--card:var(--ls-surface);--mut:var(--ls-muted);--ok:var(--ls-ok);--bad:var(--ls-danger)}
*{box-sizing:border-box;margin:0}body{background:var(--ink);color:#ececf4;font:15px/1.5 system-ui,sans-serif;padding:24px;max-width:1100px;margin:0 auto}
h1{font-size:22px;margin-bottom:2px}h1 b{background:linear-gradient(135deg,var(--brand),var(--gold));-webkit-background-clip:text;background-clip:text;color:transparent}
h2{font-size:15px;margin:0 0 12px;color:var(--gold)}
.sub{color:var(--mut);margin-bottom:24px;font-size:13px}
.ls-langsw{float:right}
.ls-lang{display:inline-block;padding:2px 7px;margin-left:4px;border-radius:6px;background:#0d0d15;color:var(--mut);font-size:12px}
.ls-lang.cur{background:var(--brand);color:#0d0d15;font-weight:700}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}
.card{background:var(--card);border:1px solid #23233247;border-radius:14px;padding:18px}
label{display:block;font-size:12px;color:var(--mut);margin:10px 0 3px}
input[type=text],textarea{width:100%;background:#0d0d15;border:1px solid #2b2b3d;border-radius:8px;color:#ececf4;padding:8px 10px;font:inherit}
input[type=color]{border:none;background:none;width:44px;height:30px;padding:0;vertical-align:middle}
button{background:linear-gradient(135deg,var(--brand),var(--gold));border:none;border-radius:8px;color:#0d0d15;font-weight:700;padding:9px 16px;margin-top:12px;cursor:pointer}
button.ghost{background:#2b2b3d;color:#ececf4;font-weight:500}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.pill{display:inline-flex;align-items:center;gap:6px;background:#0d0d15;border-radius:20px;padding:4px 12px;font-size:13px;margin:3px 4px 3px 0}
.dot{width:8px;height:8px;border-radius:50%}.ok{background:var(--ok)}.bad{background:var(--bad)}
.spon{display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid #23233247;font-size:14px}
a{color:var(--gold);text-decoration:none}
.links a{display:inline-block;background:#0d0d15;border-radius:8px;padding:8px 14px;margin:4px 6px 0 0;font-size:13px}
.note{font-size:12px;color:var(--mut);margin-top:8px}
#toast{position:fixed;bottom:20px;right:20px;background:var(--brand);color:#fff;padding:10px 18px;border-radius:10px;display:none}
.check{font-size:14px;padding:3px 0}
</style></head><body>
<h1><b>__BRAND__</b> __T_admin__</h1>
<div class="sub">__SWITCHER__ __TAGLINE__ · __T_controlpanel__ · __T_signedin__ <span id="who">…</span></div>
<div class="grid">

<div class="card"><h2>__T_branding__</h2>
<label>__T_communityname__</label><input type="text" id="b_name">
<label>__T_tagline__</label><input type="text" id="b_tag">
<label>__T_poweredby__</label><input type="text" id="b_pow">
<div class="row" style="margin-top:10px">
  <span><label>__T_cbrand__</label><input type="color" id="b_brand"></span>
  <span><label>__T_caccent__</label><input type="color" id="b_accent"></span>
  <span><label>__T_cink__</label><input type="color" id="b_ink"></span>
</div>
<button onclick="saveBrand()">__T_saveapply__</button>
<div class="note">__T_brandingnote__</div></div>

<div class="card"><h2>__T_sponsors__</h2>
<div id="sponsors"></div>
<label>__T_name__</label><input type="text" id="s_name" placeholder="Acme Corp">
<label>__T_link__</label><input type="text" id="s_url" placeholder="https://…">
<label>__T_logourl__</label><input type="text" id="s_logo" placeholder="/brand/acme.svg">
<button onclick="addSponsor()">__T_addsponsor__</button>
<div class="note">__T_sponsorsnote__</div></div>

<div class="card"><h2>__T_messaging__</h2>
<label>__T_bannerlabel__</label><input type="text" id="m_banner">
<label>__T_bannerlink__</label><input type="text" id="m_burl">
<button onclick="saveBanner()">__T_setbanner__</button> <button class="ghost" onclick="clearBanner()">__T_clear__</button>
<label style="margin-top:16px">__T_announcelabel__</label>
<textarea id="m_ann" rows="3" placeholder="__T_announceph__"></textarea>
<button onclick="announce()">__T_sendgeneral__</button></div>

<div class="card"><h2>__T_servicehealth__</h2><div id="health">__T_checking__</div>
<h2 style="margin-top:16px">__T_launchchecklist__</h2><div id="launch"></div></div>

<div class="card"><h2>__T_quicklinks__</h2><div class="links">
<a href="https://auth.__DOMAIN__/if/admin/" target="_blank">__T_link_authentik__</a>
<a href="https://live.__DOMAIN__/admin" target="_blank">__T_link_owncast__</a>
<a href="https://btcpay.__DOMAIN__" target="_blank">__T_link_btcpay__</a>
<a href="https://learn.__DOMAIN__" target="_blank">__T_link_classroom__</a>
<a href="https://premium.__DOMAIN__" target="_blank">__T_link_upgrade__</a>
<a href="https://__DOMAIN__" target="_blank">__T_link_landing__</a>
<a href="https://auth.__DOMAIN__/if/flow/community-signup/" target="_blank">__T_link_signup__</a>
</div></div>

</div>
<div id="toast"></div>
<script>
const T=__JS_T__;
const $=id=>document.getElementById(id);
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2600)}
async function api(m,p,b){const r=await fetch(p,{method:m,headers:{"Content-Type":"application/json"},body:b?JSON.stringify(b):undefined});if(!r.ok){toast(T.error+await r.text());throw 0}return r.json()}
async function load(){
  const s=await api("GET","/api/state");
  $("who").textContent=s.user||"?";
  $("b_name").value=s.brand.LS_BRAND_NAME||"";$("b_tag").value=s.brand.LS_BRAND_TAGLINE||"";
  $("b_pow").value=s.brand.LS_POWERED_BY||"";
  $("b_brand").value=s.brand.LS_COLOR_BRAND||"#7c6cff";$("b_accent").value=s.brand.LS_COLOR_ACCENT||"#ffc15e";$("b_ink").value=s.brand.LS_COLOR_INK||"#0b0b12";
  $("m_banner").value=s.banner.text||"";$("m_burl").value=s.banner.url||"";
  renderSponsors(s.sponsors);
  $("health").innerHTML=s.health.map(h=>`<span class="pill"><span class="dot ${h[1]?"ok":"bad"}"></span>${h[0]}</span>`).join("");
  $("launch").innerHTML=s.launch.map(c=>`<div class="check">${c[1]?"✅":"⬜"} ${c[0]}</div>`).join("");
}
function renderSponsors(list){
  $("sponsors").innerHTML=list.map((s,i)=>`<div class="spon"><span><a href="${s.url}" target="_blank">${s.name}</a></span><button class="ghost" style="margin:0;padding:3px 10px" onclick="delSponsor(${i})">${T.remove}</button></div>`).join("")||`<div class="note">${T.noneYet}</div>`;
}
async function saveBrand(){await api("POST","/api/branding",{LS_BRAND_NAME:$("b_name").value,LS_BRAND_TAGLINE:$("b_tag").value,LS_POWERED_BY:$("b_pow").value,LS_COLOR_BRAND:$("b_brand").value,LS_COLOR_ACCENT:$("b_accent").value,LS_COLOR_INK:$("b_ink").value});toast(T.brandingSaved)}
async function addSponsor(){const r=await api("POST","/api/sponsors",{name:$("s_name").value,url:$("s_url").value,logo:$("s_logo").value});renderSponsors(r.sponsors);$("s_name").value=$("s_url").value=$("s_logo").value="";toast(T.sponsorAdded)}
async function delSponsor(i){const r=await api("DELETE","/api/sponsors?i="+i);renderSponsors(r.sponsors);toast(T.removed)}
async function saveBanner(){await api("POST","/api/banner",{text:$("m_banner").value,url:$("m_burl").value});toast(T.bannerSet)}
async function clearBanner(){await api("POST","/api/banner",{text:"",url:""});$("m_banner").value="";toast(T.bannerCleared)}
async function announce(){const r=await api("POST","/api/announce",{text:$("m_ann").value});$("m_ann").value="";toast(T.announced+r.id)}
load();setInterval(load,30000);
</script></body></html>"""


def render_page(lang, v):
    """Substitute translations + brand values into the page template."""
    brand = html.escape(v.get("LS_BRAND_NAME", "LibreSynergy"))
    tagline = html.escape(v.get("LS_BRAND_TAGLINE", ""))
    T = i18n.t
    js_t = json.dumps({
        "error": T(lang, "common.error"),
        "brandingSaved": T(lang, "admin.toast_branding"),
        "sponsorAdded": T(lang, "admin.toast_sponsor_added"),
        "removed": T(lang, "admin.toast_removed"),
        "bannerSet": T(lang, "admin.toast_banner_set"),
        "bannerCleared": T(lang, "admin.toast_banner_cleared"),
        "announced": T(lang, "admin.toast_announced"),
        "noneYet": T(lang, "common.none_yet"),
        "remove": T(lang, "common.remove"),
    }, ensure_ascii=False)
    reps = {
        "__LANG__": lang,
        "__BRAND__": brand,
        "__TAGLINE__": tagline,
        "__DOMAIN__": v.get("LS_BASE_DOMAIN", ""),
        "__CBRAND__": v.get("LS_COLOR_BRAND", "#7c6cff"),
        "__CACCENT__": v.get("LS_COLOR_ACCENT", "#ffc15e"),
        "__SWITCHER__": i18n.switcher_html(lang, "/"),
        "__JS_T__": js_t,
        "__T_title__": T(lang, "admin.page_title", brand=brand),
        "__T_admin__": T(lang, "admin.h1_suffix"),
        "__T_controlpanel__": T(lang, "admin.control_panel"),
        "__T_signedin__": T(lang, "admin.signed_in_as"),
        "__T_branding__": T(lang, "admin.branding"),
        "__T_communityname__": T(lang, "admin.community_name"),
        "__T_tagline__": T(lang, "admin.tagline"),
        "__T_poweredby__": T(lang, "admin.powered_by"),
        "__T_cbrand__": T(lang, "admin.color_brand"),
        "__T_caccent__": T(lang, "admin.color_accent"),
        "__T_cink__": T(lang, "admin.color_ink"),
        "__T_saveapply__": T(lang, "admin.save_apply"),
        "__T_brandingnote__": T(lang, "admin.branding_note"),
        "__T_sponsors__": T(lang, "admin.sponsors"),
        "__T_name__": T(lang, "common.name"),
        "__T_link__": T(lang, "common.link"),
        "__T_logourl__": T(lang, "admin.logo_url"),
        "__T_addsponsor__": T(lang, "admin.add_sponsor"),
        "__T_sponsorsnote__": T(lang, "admin.sponsors_note"),
        "__T_messaging__": T(lang, "admin.messaging"),
        "__T_bannerlabel__": T(lang, "admin.banner_label"),
        "__T_bannerlink__": T(lang, "admin.banner_link"),
        "__T_setbanner__": T(lang, "admin.set_banner"),
        "__T_clear__": T(lang, "common.clear"),
        "__T_announcelabel__": T(lang, "admin.announce_label"),
        "__T_announceph__": T(lang, "admin.announce_placeholder"),
        "__T_sendgeneral__": T(lang, "admin.send_general"),
        "__T_servicehealth__": T(lang, "admin.service_health"),
        "__T_checking__": T(lang, "admin.checking"),
        "__T_launchchecklist__": T(lang, "admin.launch_checklist"),
        "__T_quicklinks__": T(lang, "admin.quick_links"),
        "__T_link_authentik__": T(lang, "admin.link_authentik"),
        "__T_link_owncast__": T(lang, "admin.link_owncast"),
        "__T_link_btcpay__": T(lang, "admin.link_btcpay"),
        "__T_link_classroom__": T(lang, "admin.link_classroom"),
        "__T_link_upgrade__": T(lang, "admin.link_upgrade"),
        "__T_link_landing__": T(lang, "admin.link_landing"),
        "__T_link_signup__": T(lang, "admin.link_signup"),
    }
    out = PAGE
    for k, val in reps.items():
        out = out.replace(k, val)
    return out

# ---------- http --------------------------------------------------------------
class H(BaseHTTPRequestHandler):
    def _send(self, code, body, ctype="application/json", cookie=None):
        data = body if isinstance(body, bytes) else json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        if cookie:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()
        self.wfile.write(data)

    def _admin(self):
        groups = self.headers.get("X-authentik-groups", "")
        if ADMIN_GROUP not in [g.strip() for g in groups.split("|")]:
            self._send(403, {"error": f"requires group '{ADMIN_GROUP}'"})
            return False
        return True

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/healthz":
            return self._send(200, {"ok": True})
        if not self._admin(): return
        if path == "/brand-favicon":
            try: return self._send(200, open(os.path.join(WWW, "brand", "favicon.ico"), "rb").read(), "image/x-icon")
            except Exception: return self._send(404, {"error": "no favicon"})
        if path == "/api/state":
            lang, _ = i18n.resolve(self)
            v = env_read()
            checks = [(sid, i18n.t(lang, "svc." + sid), port_check(p, hp)) for sid, p, hp in SERVICES]
            hs = {sid: ok for sid, _label, ok in checks}
            health = [[label, ok] for _sid, label, ok in checks]
            stripe_on = False
            btc_on = False
            try:
                with urllib.request.urlopen("http://127.0.0.1:9092/healthz", timeout=3) as r:
                    j = json.load(r); stripe_on = j.get("stripe", False); btc_on = j.get("btcpay", False)
            except Exception:
                btc_on = False
            launch = [
                [i18n.t(lang, "launch.stripe"), stripe_on],
                [i18n.t(lang, "launch.btcpay"), btc_on],
                [i18n.t(lang, "launch.owncast"), hs.get("owncast", False)],
                [i18n.t(lang, "launch.sso"), hs.get("sso", False)],
                [i18n.t(lang, "launch.chat"), hs.get("matrix", False)],
            ]
            return self._send(200, {
                "user": self.headers.get("X-authentik-username", ""),
                "brand": {k: v.get(k, "") for k in BRAND_KEYS + ["LS_BASE_DOMAIN"]},
                "sponsors": jload(SPONSORS, []),
                "banner": jload(BANNER, {}),
                "health": health, "launch": launch})
        if path == "/":
            lang, set_cookie = i18n.resolve(self)
            v = env_read()
            page = render_page(lang, v)
            cookie = f"ls_lang={lang}; Path=/; Max-Age=31536000; SameSite=Lax" if set_cookie else None
            return self._send(200, page.encode(), "text/html; charset=utf-8", cookie=cookie)
        self._send(404, {"error": "not found"})

    def do_POST(self):
        if not self._admin(): return
        try:
            body = json.loads(self.rfile.read(int(self.headers.get("Content-Length", 0)) or 0) or b"{}")
        except Exception:
            return self._send(400, {"error": "bad json"})
        with _lock:
            if self.path == "/api/branding":
                updates = {k: str(body.get(k, "")).strip() for k in BRAND_KEYS if k in body}
                for ck in ("LS_COLOR_BRAND", "LS_COLOR_ACCENT", "LS_COLOR_INK"):
                    if ck in updates and not re.fullmatch(r"#[0-9a-fA-F]{6}", updates[ck]):
                        return self._send(400, {"error": f"{ck} must be #rrggbb"})
                env_write(updates)
                tokens_css(env_read())
                open(FLAG, "w").write(str(time.time()))   # host cron runs apply-branding.sh
                return self._send(200, {"ok": True})
            if self.path == "/api/sponsors":
                if not body.get("name") or not body.get("url"):
                    return self._send(400, {"error": "name and url required"})
                lst = jload(SPONSORS, [])
                lst.append({"name": body["name"][:80], "url": body["url"][:300], "logo": body.get("logo", "")[:300]})
                jsave(SPONSORS, lst)
                return self._send(200, {"ok": True, "sponsors": lst})
            if self.path == "/api/banner":
                jsave(BANNER, {"text": str(body.get("text", ""))[:300], "url": str(body.get("url", ""))[:300]})
                return self._send(200, {"ok": True})
            if self.path == "/api/announce":
                text = str(body.get("text", "")).strip()
                if not text: return self._send(400, {"error": "empty"})
                ok, info = matrix_announce(text)
                return self._send(200 if ok else 502, {"ok": ok, "id": info})
        self._send(404, {"error": "not found"})

    def do_DELETE(self):
        if not self._admin(): return
        if self.path.startswith("/api/sponsors"):
            q = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            i = int(q.get("i", ["-1"])[0])
            with _lock:
                lst = jload(SPONSORS, [])
                if 0 <= i < len(lst): lst.pop(i)
                jsave(SPONSORS, lst)
            return self._send(200, {"ok": True, "sponsors": lst})
        self._send(404, {"error": "not found"})

    def log_message(self, fmt, *a):
        print(f"{time.strftime('%FT%T')} {self.headers.get('X-authentik-username','-')} {fmt % a}")

if __name__ == "__main__":
    os.makedirs(STATE, exist_ok=True)
    print(f"libresynergy-admin on {LISTEN_HOST}:{LISTEN_PORT} (admin group: {ADMIN_GROUP}, langs: {'/'.join(i18n.LANGS)})")
    ThreadingHTTPServer((LISTEN_HOST, LISTEN_PORT), H).serve_forever()
