#!/usr/bin/env bash
# ============================================================================
#  apply-branding.sh — the canonical LibreSynergy brand renderer.
#
#  This script IS the reproducibility guarantee: everything an operator brands
#  flows from libresynergy.env through here. No hand edits on the node.
#
#  What it does (each step skips gracefully when not applicable):
#    1. tokens.css   — write the per-operator palette from LS_COLOR_*
#    2. templates    — render every  *.template.*  file under www/ by
#                      substituting __LS_*__ placeholders (strip ".template")
#    3. icons        — (re)generate brand PNGs from brand/logo.svg when
#                      rsvg-convert or ImageMagick is available
#    4. Authentik    — docker exec <auth worker> ak apply_blueprint …
#    5. Frappe LMS   — Website Settings app_name + footer_powered
#    6. Jitsi        — custom-interface_config.js APP_NAME / PROVIDER_NAME
#
#  Layouts supported (env file is discovered, relative paths resolve against
#  the directory that contains libresynergy.env):
#    repo:  <root>/libresynergy.env  + <root>/www/          (this repository)
#    node:  <dir>/libresynergy/libresynergy.env + <dir>/www/ (deploy target)
#
#  Knobs (all optional):
#    LS_ENV_FILE                  explicit path to libresynergy.env
#    LS_AUTH_WORKER_CONTAINER     override Authentik worker container name
#    LS_LEARN_APP_CONTAINER      override Frappe LMS app container name
#    LS_FORCE_ICONS=1             regenerate icons even if up to date
#    LS_SKIP_SERVICES=1           only render files, skip docker/exec steps
#
#  Pure bash + coreutils. Safe to re-run (idempotent): files are only
#  rewritten when their content actually changes.
# ============================================================================
set -euo pipefail
# bash 5.2 made `&` special in ${var//pat/rep} replacements (patsub_replacement).
# Disable it so brand values containing & / \ are always substituted literally.
shopt -u patsub_replacement 2>/dev/null || true

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
say(){  printf '  • %s\n' "$*"; }
head_(){ printf '\n%s\n' "$*"; }

# ---- locate libresynergy.env ------------------------------------------------
ENV_FILE=""
for cand in "${LS_ENV_FILE:-}" \
            "$SCRIPT_DIR/../libresynergy.env" \
            "$SCRIPT_DIR/libresynergy.env" \
            "$PWD/libresynergy.env"; do
  [ -n "$cand" ] && [ -f "$cand" ] && { ENV_FILE="$(realpath "$cand")"; break; }
done
[ -n "$ENV_FILE" ] || { echo "ERROR: libresynergy.env not found (set LS_ENV_FILE=/path/to/it)"; exit 1; }
ENV_DIR="$(dirname "$ENV_FILE")"

set -a; . "$ENV_FILE"; set +a

# ---- required identity + defaults --------------------------------------------
: "${LS_BRAND_NAME:?LS_BRAND_NAME must be set in libresynergy.env}"
: "${LS_BASE_DOMAIN:?LS_BASE_DOMAIN must be set in libresynergy.env}"
: "${LS_BRAND_TAGLINE:=A self-hosted community}"
: "${LS_POWERED_BY:=LibreSynergy}"
: "${LS_COLOR_BRAND:=#7c6cff}"
: "${LS_COLOR_ACCENT:=#ffc15e}"
: "${LS_COLOR_INK:=#0b0b12}"
# Subdomains derive from LS_BASE_DOMAIN unless explicitly set.
: "${LS_APP:=app.${LS_BASE_DOMAIN}}"
: "${LS_AUTH:=auth.${LS_BASE_DOMAIN}}"
: "${LS_CHAT:=chat.${LS_BASE_DOMAIN}}"
: "${LS_MATRIX:=matrix.${LS_BASE_DOMAIN}}"
: "${LS_LEARN:=learn.${LS_BASE_DOMAIN}}"
: "${LS_MEET:=meet.${LS_BASE_DOMAIN}}"
: "${LS_LIVE:=live.${LS_BASE_DOMAIN}}"
# Default community room for the app-shell chat panel. Empty is valid — the
# panel then falls back gracefully (no room preselected).
: "${LS_MATRIX_ROOM:=}"

# ---- resolve www/ and data/ against the env file's directory -----------------
resolve_dir(){ # $1 configured value (may be relative/empty), $2… fallbacks
  local v="$1"; shift
  if [ -n "$v" ]; then
    case "$v" in /*) ;; *) v="$ENV_DIR/$v";; esac
    v="$(realpath -m "$v")"
    [ -d "$v" ] && { printf '%s' "$v"; return; }
  fi
  local f
  for f in "$@"; do [ -d "$f" ] && { printf '%s' "$(realpath -m "$f")"; return; }; done
  # nothing exists yet — fall back to the configured (or first fallback) path
  printf '%s' "${v:-$1}"
}
WWW_DIR="$(resolve_dir "${LS_WWW_DIR:-}" "$ENV_DIR/www" "$ENV_DIR/../www")"
DATA_DIR="$(resolve_dir "${LS_DATA_DIR:-}" "$ENV_DIR/data" "$ENV_DIR/../data")"
BRAND_DIR="$WWW_DIR/brand"

echo "LibreSynergy → applying brand '${LS_BRAND_NAME}' (${LS_BASE_DOMAIN})"
say "env:  $ENV_FILE"
say "www:  $WWW_DIR"

# Write $2 to path $1 only when content changed. Echoes CHANGED/UNCHANGED.
write_if_changed(){
  local path="$1" tmp
  tmp="$(mktemp "${path}.tmp.XXXXXX")"
  printf '%s' "$2" > "$tmp"
  if cmp -s "$tmp" "$path" 2>/dev/null; then rm -f "$tmp"; echo UNCHANGED
  else mv "$tmp" "$path"; echo CHANGED; fi
}

# ---- 1) Palette → central CSS tokens (read by shell, landing, checkout) ------
head_ "[1/6] Brand tokens"
install -d "$BRAND_DIR"
TOKENS_CSS="/* ${LS_BRAND_NAME} brand tokens — powered by ${LS_POWERED_BY}. Generated by apply-branding.sh */
:root{
  --ls-ink:${LS_COLOR_INK};
  --ls-brand:${LS_COLOR_BRAND};
  --ls-gold:${LS_COLOR_ACCENT};
  --ls-gradient:linear-gradient(135deg,${LS_COLOR_BRAND} 0%,${LS_COLOR_ACCENT} 100%);
}
"
say "tokens.css → $BRAND_DIR/tokens.css ($(write_if_changed "$BRAND_DIR/tokens.css" "$TOKENS_CSS"))"

# ---- 2) Render *.template.* files under www/ ---------------------------------
head_ "[2/6] Templates"
PLACEHOLDERS=(LS_BRAND_NAME LS_BRAND_TAGLINE LS_POWERED_BY LS_BASE_DOMAIN
              LS_APP LS_CHAT LS_MATRIX LS_MATRIX_ROOM LS_LEARN LS_MEET
              LS_LIVE LS_AUTH
              LS_COLOR_BRAND LS_COLOR_ACCENT LS_COLOR_INK)
N_RENDERED=0; N_FRESH=0; LEFTOVER_WARN=""
if [ -d "$WWW_DIR" ]; then
  while IFS= read -r -d '' src; do
    case "$src" in
      *.template.*) out="${src/.template./.}" ;;
      *.template)   out="${src%.template}"    ;;
    esac
    # read template preserving trailing newlines, substitute placeholders
    content="$(cat "$src"; printf x)"; content="${content%x}"
    for ph in "${PLACEHOLDERS[@]}"; do
      content="${content//__${ph}__/${!ph}}"
    done
    rel_out="${out#"$WWW_DIR"/}"
    if [ "$(write_if_changed "$out" "$content")" = CHANGED ]; then
      say "rendered  $rel_out"; N_FRESH=$((N_FRESH+1))
    else
      say "unchanged $rel_out"
    fi
    N_RENDERED=$((N_RENDERED+1))
    # flag any placeholder this script does not know about
    left="$(grep -oE '__LS_[A-Z0-9_]+__' "$out" 2>/dev/null | sort -u | tr '\n' ' ' || true)"
    [ -n "$left" ] && LEFTOVER_WARN+="    $rel_out: $left"$'\n'
  done < <(find "$WWW_DIR" -type f \( -name '*.template.*' -o -name '*.template' \) -print0 | sort -z)
  [ "$N_RENDERED" -eq 0 ] && say "no *.template.* files under $WWW_DIR (nothing to render)"
  if [ -n "$LEFTOVER_WARN" ]; then
    printf '  ! WARNING: unresolved placeholders remain:\n%s' "$LEFTOVER_WARN"
  fi
else
  say "www dir not found — skipped"
fi

# ---- 3) Icons from brand/logo.svg --------------------------------------------
head_ "[3/6] Icons"
LOGO="$BRAND_DIR/logo.svg"
render_icon(){ # $1 out.png  $2 size  $3 background ("none" or a color)
  local out="$1" size="$2" bg="$3"
  if [ "${LS_FORCE_ICONS:-0}" != 1 ] && [ -f "$out" ] && ! [ "$LOGO" -nt "$out" ]; then
    say "up-to-date $(basename "$out")"; return 0
  fi
  if command -v rsvg-convert >/dev/null 2>&1; then
    if [ "$bg" = none ]; then rsvg-convert -w "$size" -h "$size" -o "$out" "$LOGO"
    else rsvg-convert -w "$size" -h "$size" -b "$bg" -o "$out" "$LOGO"; fi
  elif command -v magick >/dev/null 2>&1; then
    magick -background "$bg" -density 384 "$LOGO" -resize "${size}x${size}" -gravity center -extent "${size}x${size}" "$out"
  elif command -v convert >/dev/null 2>&1; then
    convert -background "$bg" -density 384 "$LOGO" -resize "${size}x${size}" -gravity center -extent "${size}x${size}" "$out"
  else
    return 1
  fi
  say "generated  $(basename "$out") (${size}x${size})"
}
if [ ! -f "$LOGO" ]; then
  say "no $LOGO — skipped (drop a logo.svg in $BRAND_DIR to enable)"
elif ! command -v rsvg-convert >/dev/null 2>&1 && ! command -v magick >/dev/null 2>&1 && ! command -v convert >/dev/null 2>&1; then
  say "no rsvg-convert or ImageMagick on this host — skipped (icons keep their current PNGs)"
else
  render_icon "$BRAND_DIR/icon-192.png"          192 none               || say "icon-192.png failed (kept existing)"
  render_icon "$BRAND_DIR/icon-512.png"          512 none               || say "icon-512.png failed (kept existing)"
  render_icon "$BRAND_DIR/apple-touch-icon.png"  180 "$LS_COLOR_INK"    || say "apple-touch-icon.png failed (kept existing)"
fi

# ---- service propagation (steps 4–6) ------------------------------------------
running_containers(){ docker ps --format '{{.Names}} {{.Image}}' 2>/dev/null; }
DOCKER_OK=1
if [ "${LS_SKIP_SERVICES:-0}" = 1 ]; then
  DOCKER_OK=0; head_ "[4-6/6] Services"; say "LS_SKIP_SERVICES=1 — skipped"
elif ! command -v docker >/dev/null 2>&1; then
  DOCKER_OK=0; head_ "[4-6/6] Services"; say "docker not available on this host — skipped (run on the node)"
fi

if [ "$DOCKER_OK" = 1 ]; then
  # ---- 4) Authentik — re-apply the branding blueprint(s) ---------------------
  head_ "[4/6] Authentik"
  # worker container: name has "worker" AND (name starts with auth… OR image is authentik)
  AUTH_C="${LS_AUTH_WORKER_CONTAINER:-$(running_containers \
    | awk '$1 ~ /worker/ && ($1 ~ /^auth/ || $2 ~ /authentik/) {print $1; exit}')}"
  if [ -n "$AUTH_C" ]; then
    BPS="$(docker exec "$AUTH_C" sh -c 'ls /blueprints/custom/*.yaml /blueprints/custom/*.yml 2>/dev/null' 2>/dev/null || true)"
    if [ -n "$BPS" ]; then
      for bp in $BPS; do
        if docker exec "$AUTH_C" ak apply_blueprint "$bp" >/dev/null 2>&1; then
          say "applied blueprint $bp (container $AUTH_C)"
        else
          say "blueprint $bp failed to apply (container $AUTH_C)"
        fi
      done
    else
      say "no custom blueprints in $AUTH_C:/blueprints/custom — skipped"
    fi
  else
    say "no Authentik worker container running — skipped"
  fi

  # ---- 5) Frappe LMS — app name + footer -------------------------------------
  head_ "[5/6] Frappe LMS"
  # app container: learn…-app-N by name, or an -app-N container on a frappe/lms image
  LEARN_C="${LS_LEARN_APP_CONTAINER:-$(running_containers \
    | awk '($1 ~ /^learn.*[-_]app[-_][0-9]+$/) || ($1 ~ /[-_]app[-_][0-9]+$/ && $2 ~ /frappe|lms/) {print $1; exit}')}"
  if [ -n "$LEARN_C" ]; then
    BN_PY="${LS_BRAND_NAME//\'/\\\'}"; PB_PY="${LS_POWERED_BY//\'/\\\'}"
    if docker exec "$LEARN_C" bash -lc "cd /home/frappe/frappe-bench && \
        echo \"import frappe; d=frappe.get_doc('Website Settings'); d.app_name='${BN_PY}'; d.footer_powered='Powered by ${PB_PY}'; d.save(ignore_permissions=True); frappe.db.commit()\" \
        > /tmp/ls_brand.py && bench --site ${LS_LEARN} console < /tmp/ls_brand.py" >/dev/null 2>&1; then
      say "Website Settings app_name set to '${LS_BRAND_NAME}' (container $LEARN_C)"
    else
      say "bench console failed (container $LEARN_C) — skipped"
    fi
  else
    say "no Frappe LMS app container running — skipped"
  fi

  # ---- 6) Jitsi — app/provider name -------------------------------------------
  head_ "[6/6] Jitsi"
  JF="$DATA_DIR/jitsi/web/custom-interface_config.js"
  if [ -f "$JF" ]; then
    SED_BN="$(printf '%s' "$LS_BRAND_NAME" | sed -e 's/[&/\\]/\\&/g')"
    SED_ARGS=(
      -e "s/interfaceConfig.APP_NAME = .*/interfaceConfig.APP_NAME = '${SED_BN}';/"
      -e "s/interfaceConfig.PROVIDER_NAME = .*/interfaceConfig.PROVIDER_NAME = '${SED_BN}';/"
    )
    if sed -i "${SED_ARGS[@]}" "$JF" 2>/dev/null || sudo -n sed -i "${SED_ARGS[@]}" "$JF" 2>/dev/null; then
      say "APP_NAME/PROVIDER_NAME set to '${LS_BRAND_NAME}' (recreate the meet web container to apply)"
    else
      say "could not edit $JF (permissions) — run with sudo on the node"
    fi
  else
    say "no $JF — skipped"
  fi
fi

# ---- summary ------------------------------------------------------------------
head_ "Summary"
say "brand:     ${LS_BRAND_NAME} — '${LS_BRAND_TAGLINE}' @ ${LS_BASE_DOMAIN}"
say "palette:   brand ${LS_COLOR_BRAND} · accent ${LS_COLOR_ACCENT} · ink ${LS_COLOR_INK}"
say "templates: ${N_RENDERED} found, ${N_FRESH} (re)rendered"
say "tokens:    $BRAND_DIR/tokens.css"
echo
echo "Done. Recreate caddy so the edge serves the new tree (deploy-node.sh does"
echo "this), and the Jitsi web container if its branding changed."
